### PR TITLE
Fix #54 by setting dimension of cell arrays

### LINKED ISSUE #54: Cell Arrays import as Lists and lose dimensionality
# Description
All matlab `Cell Array` data ends up imported without its dimensionality preserved. It ends up in R as a 1 dimensional `List`.

# Expected Behavior
Imported Cell Arrays maintain the dimensions they posess when opened by matlab and are not coerced into lists (which are by definition 1-dimensional).

# Observed Behavior
A 9x27 array becomes a 243-element list when imported. A minimal test-case 2x2 cell array becomes a 4-element list when imported. 

# Steps to Reproduce
Use [cell array test case.zip](https://github.com/HenrikBengtsson/R.matlab/files/8950911/cell.array.test.case.zip), or...
1. Create a 2-dimensional `cell array` in matlab and export to .mat file: 
2x2
2. In an R environment with R.matlab loaded, import the .mat file:
```
file = readMat("~/GitHub/Behavior-autoanalysis/Only_2by2table.mat")
```
3. Observe that the `cell array` imported into an R `list`, and its dimensionality has been lost:
```
class(file$source.list)
# > class(file$source.list)
# [1] "list"

print(file$source.list)
# > print(file$source.list)
# [[1]]
# [[1]][[1]]
# [,1]
# [1,] "tone"
#
#
# [[2]]
# [[2]][[1]]
# [,1]
# [1,] "tone"
#
#
# [[3]]
# [[3]][[1]]
# [,1]
# [1,]   30
#
#
# [[4]]
# [[4]][[1]]
# [,1]
# [1,]   40
```

# Other notes
I realize that this data could be stored in matlab as a `table` or a `matrix` both of which import correctly. Unfortunately, I am not in control of the data being imported in my application.

# Technical information
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages: [1] R.matlab_3.6.2

### PR DESCRIPTION
**Pull request by tofof**
Resolves #54.

Uses same technique used during import of mxSTRUCT_CLASS to set dimensionality while importing from mxCELL_CLASS .

### CODE REVIEW

**Comment by HenrikBengtsson** [comment]
Thank you for this and the detailed report.

Would you mind adding a package test too, i.e. a `tests/*.R` file that verifies the fix based on your `Only_2by2table.mat`? That MAT file would go into the [inst/mat-files](https://github.com/HenrikBengtsson/R.matlab/tree/develop/inst/mat-files) folder.  This way, we can make sure this bug doesn't sneak back in later on.

**Comment by HenrikBengtsson** [comment]
> Thank you for this and the detailed report.
> 
> Would you mind adding a package test too, i.e. a `tests/*.R` file that verifies the fix based on your `Only_2by2table.mat`? That MAT file would go into the [inst/mat-files](https://github.com/HenrikBengtsson/R.matlab/tree/develop/inst/mat-files) folder. This way, we can make sure this bug doesn't sneak back in later on.

I need to submit an updated version of **R.matlab** to CRAN by September 8, 2022.  It would be great if this could be incorporated by then.  In order to do that, I'll need a package test that produces an error with the current CRAN version of **R.matlab**.

**Comment by tofof** [comment]
Done.

**Comment by HenrikBengtsson** [comment]
Thank you

**Comment by HenrikBengtsson** [comment]
FYI, I've dropped the `tryCatch()` in the package test, because `readMat()` should not give an error. It's only the dimension that was lost.

**Pull request merged**
